### PR TITLE
feat: kwargs arguments MSU.Table function

### PR DESCRIPTION
**Pull request by TaroEld**
This adds a function to get a key word arguments table that employs delegation. The goal is to allow for easier handling of large numbers of arguments where ordering might become cumbersome. Due to the delegation, `this` will first refer to the passed options, and then to the passed 'default' arguments.

### CODE REVIEW

**Review by Enduriel — APPROVED** [review]

**Comment by LordMidas** [comment]
Could you please write up a use-case example of this?

**Comment by LordMidas** [comment]
Based on discussion in Discord, we basically need a way to verify arg names and potentially allow modders to add more args.

**Comment by LordMidas** [comment]
Also the `MSU.Table` namespace is specifically for working with squirrel tables (an indirect way of adding metamethods to `table` analogous to `array.` functions.). This `getKwargs` function should be part of the `MSU.` global namespace.

**Comment by LordMidas** [comment]
Based on discussion in Discord we decided to go with something like:
```squirrel
function getKwargs( _passedArgs, _defaultArgs )
{
	if (_passedArgs = null) _passedArgs = {};
	foreach (key, value in _passedArgs)
	{
		if (!(key in _defaultArgs))
		{
			::logError(key + " is not a valid keyword argument for this function. If you are trying to add a new argument, you must hook the function and expand the default arguments table");
			throw ::MSU.Exception.InvalidValue(key);
		}
	}

	_passedArgs.setdelegate(_defaultArgs);
	return _passedArgs;
}
```

And then we enforce a standard that kwargs must be used as follows i.e. **with a null argument and an empty table argument**.

```squirrel
function myFunc( _options = null, _defaultArgs = {} )
{
	_defaultArgs.ArgName1 = false;
	_defaultArgs.ArgName2 = true;

	local args = ::MSU.getKwargs(_options, _defaultArgs);
}
```

And for hooking:

```squirrel
local someFunc = o.someFunc;
o.someFunc = function( _options = null, _defaultArgs = {} )
{
	_defaultArgs.MyAdditionalArg = 5;
	someFunc(_options, _defaultArgs);
}
```

**Review by LordMidas — CHANGES_REQUESTED** [review]
1. Please move to `::MSU.` namespace.
2. I prefer the name `getKwargs` over `getKwargsTable`.

Based on discussion in Discord we decided to go with something like:
```squirrel
function getKwargs( _passedArgs, _defaultArgs )
{
	if (_passedArgs = null) _passedArgs = {};
	foreach (key, value in _passedArgs)
	{
		if (!(key in _defaultArgs))
		{
			::logError(key + " is not a valid keyword argument for this function. If you are trying to add a new argument, you must hook the function and expand the default arguments table");
			throw ::MSU.Exception.InvalidValue(key);
		}
	}

	_passedArgs.setdelegate(_defaultArgs);
	return _passedArgs;
}
```

And then we enforce a standard that kwargs must be used as follows i.e. **with a null argument and an empty table argument**.

```squirrel
function myFunc( _options = null, _defaultArgs = {} )
{
	_defaultArgs.ArgName1 = false;
	_defaultArgs.ArgName2 = true;

	local args = ::MSU.getKwargs(_options, _defaultArgs);
}
```

And for hooking:

```squirrel
local someFunc = o.someFunc;
o.someFunc = function( _options = null, _defaultArgs = {} )
{
	_defaultArgs.MyAdditionalArg = 5;
	someFunc(_options, _defaultArgs);
}
```

**Comment by Enduriel** [comment]
We'll be taking a different approach with this after a lot of discussion so closing this PR in favor of a different one with the new approach.

**Pull request closed without merging**
